-- Task C.3 Reports 5-8
-- REPORT 5
SELECT BOOKINGMONTH AS "Booking month",
    PASSENGERAGEGROUPDESC AS "Passenger age group description",
    CARBODYTYPE AS "Car body type",
    SUM(NO_OF_BOOKING_RECORDS) AS "Number of Bookings"
FROM BOOKING_FACT_V1
GROUP BY ROLLUP (BOOKINGMONTH, PASSENGERAGEGROUPDESC, CARBODYTYPE)
ORDER BY TO_DATE(BOOKINGMONTH, 'Month'), PASSENGERAGEGROUPDESC, CARBODYTYPE;

-- REPORT 6
SELECT BOOKINGMONTH AS "Booking month",
    PASSENGERAGEGROUPDESC AS "Passenger age group description",
    CARBODYTYPE AS "Car body type",
    SUM(NO_OF_BOOKING_RECORDS) AS "Number of Bookings"
FROM BOOKING_FACT_V1
GROUP BY BOOKINGMONTH, ROLLUP(PASSENGERAGEGROUPDESC, CARBODYTYPE)
ORDER BY TO_DATE(BOOKINGMONTH, 'Month'), PASSENGERAGEGROUPDESC, CARBODYTYPE;

-- REPORT 7
SELECT BOOKINGMONTH AS "Booking Month", PASSENGERAGEGROUPDESC AS "Passenger Age Group Description", SUM(NO_OF_BOOKING_RECORDS) AS "Number of Booking Records",
ROUND(AVG(SUM(NO_OF_BOOKING_RECORDS)) OVER (ORDER BY BOOKINGMONTH ROWS 2 PRECEDING),2) AS "Moving 3 Months Average"
FROM BOOKING_FACT_V1
GROUP BY BOOKINGMONTH, PASSENGERAGEGROUPDESC
ORDER BY TO_DATE(BOOKINGMONTH, 'Month');

-- REPORT 8
SELECT TEAMID AS "Team ID", CARBODYTYPE AS "Car Body Type", 
SUM(TOTAL_MAINTENANCE_COST) AS "Total Maintenance Cost",
TO_CHAR(SUM(SUM(TOTAL_MAINTENANCE_COST)) OVER (PARTITION BY TEAMID ORDER BY TEAMID, 
CARBODYTYPE ROWS UNBOUNDED PRECEDING), '9,999,999.99') AS "Cumulative Maintenance Cost"
FROM MAINTENANCE_FACT_V1
GROUP BY TEAMID, CARBODYTYPE;