-- Task C.2
-- Creating Star Schema v1 (LEVEL 1)
-- Create car body type dimension
DROP TABLE CARBODYTYPE_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE CARBODYTYPE_DIM_V1 AS
    SELECT DISTINCT CARBODYTYPE, NUMSEATS FROM CAR;
    
SELECT * FROM CARBODYTYPE_DIM_V1;

-- Create faculty dimension
DROP TABLE FACULTY_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE FACULTY_DIM_V1 AS 
    SELECT DISTINCT FACULTYID FROM PASSENGER;
    
SELECT * FROM FACULTY_DIM_V1;

-- Create passenger age group dimension
DROP TABLE PASSENGERAGEGROUP_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE PASSENGERAGEGROUP_DIM_V1 (
    PASSENGERAGEGROUPID   VARCHAR2(10),
    PASSENGERAGEGROUPDESC    VARCHAR2(50),
    MAXAGE    NUMBER,
    MINAGE      NUMBER
);

INSERT INTO PASSENGERAGEGROUP_DIM_V1 VALUES('Group1', 'Young adults', 35, 18);
INSERT INTO PASSENGERAGEGROUP_DIM_V1 VALUES('Group2', 'Middle-aged adults', 59, 36);
INSERT INTO PASSENGERAGEGROUP_DIM_V1 VALUES('Group3', 'Old-aged adults', NULL, 60
);

SELECT * FROM PASSENGERAGEGROUP_DIM_V1;

-- Create booking month dimension
DROP TABLE BOOKINGMONTH_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKINGMONTH_DIM_V1 AS
    SELECT DISTINCT TO_CHAR(BOOKINGDATE, 'Month') AS BOOKINGMONTH 
    FROM BOOKING 
    ORDER BY TO_DATE(BOOKINGMONTH, 'Month');
    
SELECT * FROM BOOKINGMONTH_DIM_V1;

-- Create maintenance type dimension
DROP TABLE MAINTENANCETYPE_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETYPE_DIM_V1 AS
    SELECT MAINTENANCETYPE FROM MAINTENANCETYPE;
    
SELECT * FROM MAINTENANCETYPE_DIM_V1;

-- Create research center dimension
DROP TABLE RESEARCHCENTER_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE RESEARCHCENTER_DIM_V1 AS
    SELECT CENTERID FROM RESEARCHCENTER;
    
SELECT * FROM RESEARCHCENTER_DIM_V1;

-- Create team center bridge table
DROP TABLE TEAMCENTER_BRIDGE_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE TEAMCENTER_BRIDGE_V1 AS
    SELECT * FROM BELONGTO;
    
SELECT * FROM TEAMCENTER_BRIDGE_V1;

-- Create maintenance team dimension
DROP TABLE MAINTENANCETEAM_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETEAM_DIM_V1 AS
    SELECT T.TEAMID, ROUND(1.0/COUNT(B.CENTERID), 2) AS RESEARCHCENTER_WEIGHTFACTOR,
           LISTAGG(B.CENTERID, ' ') WITHIN GROUP (ORDER BY B.CENTERID) AS RESEARCHCENTER_LISTAGG
    FROM MAINTENANCETEAM T, BELONGTO B
    WHERE T.TEAMID=B.TEAMID
    GROUP BY T.TEAMID;
    
SELECT * FROM MAINTENANCETEAM_DIM_V1;

-- Create error code dimension
DROP TABLE ERRORCODE_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ERRORCODE_DIM_V1 AS
    SELECT ERRORCODE FROM ERROR;
    
SELECT * FROM ERRORCODE_DIM_V1;

-- Create accident zone dimension
DROP TABLE ACCIDENTZONE_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTZONE_DIM_V1 AS
    SELECT DISTINCT ACCIDENTZONE FROM ACCIDENTINFO ORDER BY ACCIDENTZONE;
    
SELECT * FROM ACCIDENTZONE_DIM_V1;

-- Create car damage severity dimension
DROP TABLE CARDAMAGESEVERITY_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE CARDAMAGESEVERITY_DIM_V1 AS
    SELECT DISTINCT CAR_DAMAGE_SEVERITY FROM ACCIDENTINFO;
    
SELECT * FROM CARDAMAGESEVERITY_DIM_V1;

-- Create car dimension
DROP TABLE CAR_DIM_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE CAR_DIM_V1 AS
    SELECT REGISTRATIONNO, CARBODYTYPE FROM CAR;
    
SELECT * FROM CAR_DIM_V1;

-- Create temporary Booking Fact table for star schema v-1 (level 1)
DROP TABLE TEMP_BOOKING_FACT_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE TEMP_BOOKING_FACT_V1 AS
    SELECT B.BOOKINGID, P.PASSENGERAGE, B.BOOKINGDATE, P.FACULTYID, C.CARBODYTYPE
    FROM BOOKING B, CAR C, PASSENGER P
    WHERE B.PASSENGERID=P.PASSENGERID AND
          B.REGISTRATIONNO=C.REGISTRATIONNO;
SELECT * FROM TEMP_BOOKING_FACT_V1;

ALTER TABLE TEMP_BOOKING_FACT_V1
DROP COLUMN PASSENGERAGEGROUPID;

ALTER TABLE TEMP_BOOKING_FACT_V1
ADD (PASSENGERAGEGROUPID VARCHAR2(10));

UPDATE TEMP_BOOKING_FACT_V1
SET PASSENGERAGEGROUPID='Group1'
WHERE PASSENGERAGE>='18' AND
      PASSENGERAGE<='35';
      
UPDATE TEMP_BOOKING_FACT_V1
SET PASSENGERAGEGROUPID='Group2'
WHERE PASSENGERAGE>='36' AND
      PASSENGERAGE<='59';
      
UPDATE TEMP_BOOKING_FACT_V1
SET PASSENGERAGEGROUPID='Group3'
WHERE PASSENGERAGE>='60';

ALTER TABLE TEMP_BOOKING_FACT_V1
DROP COLUMN BOOKINGMONTH;

ALTER TABLE TEMP_BOOKING_FACT_V1
ADD (BOOKINGMONTH VARCHAR2(10));

UPDATE TEMP_BOOKING_FACT_V1  
SET BOOKINGMONTH=TO_CHAR(BOOKINGDATE, 'Month');

SELECT * FROM TEMP_BOOKING_FACT_V1;

-- Create Booking Fact table for star schema v-1 (level 1)
DROP TABLE BOOKING_FACT_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKING_FACT_V1 AS
    SELECT TF.PASSENGERAGEGROUPID, P.PASSENGERAGEGROUPDESC, TF.BOOKINGMONTH, TF.FACULTYID, TF.CARBODYTYPE, COUNT(TF.BOOKINGID) AS NO_OF_BOOKING_RECORDS
    FROM TEMP_BOOKING_FACT_V1 TF, PASSENGERAGEGROUP_DIM_V1 P
    WHERE TF.PASSENGERAGEGROUPID=P.PASSENGERAGEGROUPID
    GROUP BY TF.PASSENGERAGEGROUPID, P.PASSENGERAGEGROUPDESC, TF.BOOKINGMONTH, TF.FACULTYID, TF.CARBODYTYPE
    ORDER BY TF.CARBODYTYPE, TF.PASSENGERAGEGROUPID, TO_DATE(TF.BOOKINGMONTH, 'MON');
    
SELECT * FROM BOOKING_FACT_V1;

-- Create Maintenance Fact table for star schema v-1 (level 1)
DROP TABLE MAINTENANCE_FACT_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCE_FACT_V1 AS
    SELECT M.TEAMID, C.CARBODYTYPE, M.MAINTENANCETYPE,
          COUNT(M.MAINTENANCEID) AS NO_OF_MAINTENANCE_RECORDS,
          SUM(M.MAINTENANCECOST) AS TOTAL_MAINTENANCE_COST
    FROM MAINTENANCE M, CAR C
    WHERE M.REGISTRATIONNO=C.REGISTRATIONNO
    GROUP BY M.TEAMID, C.CARBODYTYPE, M.MAINTENANCETYPE
    ORDER BY TEAMID;
    
SELECT * FROM MAINTENANCE_FACT_V1;

-- Create Accident Fact table for star schema v-1 (level 1)
DROP TABLE ACCIDENT_FACT_V1 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENT_FACT_V1 AS
    SELECT E.ERRORCODE, C.REGISTRATIONNO, C.CARBODYTYPE, A.ACCIDENTZONE, A.CAR_DAMAGE_SEVERITY, COUNT(A.ACCIDENTID) AS NO_OF_ACCIDENT_RECORDS
    FROM ACCIDENTINFO A, ERROR E, CAR C, CARACCIDENT CA
    WHERE A.ERRORCODE=E.ERRORCODE AND
          A.ACCIDENTID=CA.ACCIDENTID AND
          CA.REGISTRATIONNO=C.REGISTRATIONNO
    GROUP BY E.ERRORCODE, C.REGISTRATIONNO, C.CARBODYTYPE, A.ACCIDENTZONE, A.CAR_DAMAGE_SEVERITY
    ORDER BY ERRORCODE, NO_OF_ACCIDENT_RECORDS DESC, ACCIDENTZONE, CAR_DAMAGE_SEVERITY;
    
SELECT * FROM ACCIDENT_FACT_V1;

--------------------------------------------------------------------------------

-- Creating Star Schema v2 (LEVEL 0)
-- Create booking dimension
DROP TABLE BOOKING_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKING_DIM_V2 AS
SELECT DISTINCT BOOKINGID, BOOKINGDATE
FROM BOOKING
ORDER BY BOOKINGID;

SELECT * FROM BOOKING_DIM_V2;

-- Create passenger dimension
DROP TABLE PASSENGER_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE PASSENGER_DIM_V2 AS
SELECT DISTINCT PASSENGERID, PASSENGERAGE, FACULTYID
FROM PASSENGER
ORDER BY PASSENGERID;

SELECT * FROM PASSENGER_DIM_V2;

-- Create faculty dimension
DROP TABLE FACULTY_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE FACULTY_DIM_V2 AS
SELECT DISTINCT FACULTYID
FROM FACULTY
ORDER BY FACULTYID;

SELECT * FROM FACULTY_DIM_V2;

-- Create car dimension
DROP TABLE CAR_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE CAR_DIM_V2 AS
SELECT DISTINCT REGISTRATIONNO, CARBODYTYPE, NUMSEATS
FROM CAR
ORDER BY REGISTRATIONNO;

SELECT * FROM CAR_DIM_V2;

-- Create booking fact for star schema v-2 (level 0)
DROP TABLE BOOKING_FACT_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKING_FACT_V2 AS
SELECT B.BOOKINGID, P.PASSENGERID, C.REGISTRATIONNO,
COUNT(B.BOOKINGID) AS NO_OF_BOOKING_RECORDS
FROM PASSENGER P, BOOKING B, CAR C
WHERE P.PASSENGERID = B.PASSENGERID
AND C.REGISTRATIONNO = B.REGISTRATIONNO
GROUP BY P.PASSENGERID, B.BOOKINGID, C.REGISTRATIONNO
ORDER BY B.BOOKINGID;

SELECT * FROM BOOKING_FACT_V2;

-- Create maintenance dimension
DROP TABLE MAINTENANCE_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCE_DIM_V2 AS
SELECT DISTINCT MAINTENANCEID
FROM MAINTENANCE
ORDER BY MAINTENANCEID;

SELECT * FROM MAINTENANCE_DIM_V2;

-- Create Maintenance type dimension
DROP TABLE MAINTENANCETYPE_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETYPE_DIM_V2 AS
SELECT DISTINCT MAINTENANCETYPE
FROM MAINTENANCETYPE
ORDER BY MAINTENANCETYPE;

SELECT * FROM MAINTENANCETYPE_DIM_V2;

-- Create maintenance team dimension
DROP TABLE MAINTENANCETEAM_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETEAM_DIM_V2 AS
SELECT DISTINCT M.TEAMID,
(1.0/COUNT(B.CENTERID)) AS RESEARCHCENTER_WEIGHTFACTOR,
LISTAGG(B.CENTERID, '_') WITHIN GROUP (ORDER BY B.CENTERID) AS RESEARCHCENTER_LISTAGG
FROM MAINTENANCETEAM M, BELONGTO B
WHERE M.TEAMID = B.TEAMID
GROUP BY M.TEAMID
ORDER BY M.TEAMID;

SELECT * FROM MAINTENANCETEAM_DIM_V2;

-- Create maintenance team and research center bridge table
DROP TABLE TEAMCENTER_BRIDGE_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE TEAMCENTER_BRIDGE_V2 AS
SELECT *
FROM BELONGTO
ORDER BY TEAMID;

SELECT * FROM TEAMCENTER_BRIDGE_V2;

-- Create research center dimension
DROP TABLE RESEARCHCENTER_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE RESEARCHCENTER_DIM_V2 AS
SELECT DISTINCT CENTERID
FROM RESEARCHCENTER
ORDER BY CENTERID;

SELECT * FROM RESEARCHCENTER_DIM_V2;

-- Create Maintenance Fact table for star schema v-2 (level 0)
DROP TABLE MAINTENANCE_FACT_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCE_FACT_V2 AS
SELECT M.MAINTENANCEID, C.REGISTRATIONNO, M.MAINTENANCETYPE, M.TEAMID,
SUM(M.MAINTENANCECOST) AS TOTAL_MAINTENANCE_COST,
COUNT(M.MAINTENANCEID) AS NO_OF_MAINTENANCE_RECORDS
FROM MAINTENANCE M, MAINTENANCETYPE MTY, MAINTENANCETEAM MTE, CAR C
WHERE M.MAINTENANCETYPE = MTY.MAINTENANCETYPE
AND M.TEAMID = MTE.TEAMID
AND M.REGISTRATIONNO = C.REGISTRATIONNO
GROUP BY M.MAINTENANCEID, C.REGISTRATIONNO, M.MAINTENANCETYPE, M.TEAMID
ORDER BY M.MAINTENANCEID;

SELECT * FROM MAINTENANCE_FACT_V2;

-- Create error dimension
DROP TABLE ERRORCODE_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ERRORCODE_DIM_V2 AS
SELECT DISTINCT ERRORCODE
FROM ERROR
ORDER BY ERRORCODE;

SELECT * FROM ERRORCODE_DIM_V2;

-- Create accident zone dimension
DROP TABLE ACCIDENTZONE_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTZONE_DIM_V2 AS
SELECT DISTINCT ACCIDENTZONE
FROM ACCIDENTINFO
ORDER BY ACCIDENTZONE;

SELECT * FROM ACCIDENTZONE_DIM_V2;

-- Create car damage severity dimension
DROP TABLE CARDAMAGESEVERITY_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE CARDAMAGESEVERITY_DIM_V2 AS 
SELECT DISTINCT CAR_DAMAGE_SEVERITY
FROM ACCIDENTINFO
ORDER BY CAR_DAMAGE_SEVERITY;

SELECT * FROM CARDAMAGESEVERITY_DIM_V2;

-- Create accident info dimension
DROP TABLE ACCIDENTINFO_DIM_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTINFO_DIM_V2 AS
SELECT DISTINCT A.ACCIDENTID, 
(1.0/COUNT(C.REGISTRATIONNO)) AS CAR_WEIGHTFACTOR,
LISTAGG(C.REGISTRATIONNO, '_') WITHIN GROUP (ORDER BY C.REGISTRATIONNO) AS CAR_LISTAGG
FROM ACCIDENTINFO A, CARACCIDENT C
WHERE A.ACCIDENTID = C.ACCIDENTID
GROUP BY A.ACCIDENTID
ORDER BY A.ACCIDENTID;

SELECT * FROM ACCIDENTINFO_DIM_V2;

-- Create accidentinfo and car bridge table
DROP TABLE ACCIDENTINFOCAR_BRIDGE_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTINFOCAR_BRIDGE_V2 AS
SELECT *
FROM CARACCIDENT
ORDER BY ACCIDENTID;

SELECT * FROM ACCIDENTINFOCAR_BRIDGE_V2;

-- Create accident fact 
DROP TABLE ACCIDENT_FACT_V2 CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENT_FACT_V2 AS
SELECT DISTINCT A.ACCIDENTID, A.ACCIDENTZONE, A.ERRORCODE, A.CAR_DAMAGE_SEVERITY,
COUNT(A.ACCIDENTID) AS NO_OF_ACCIDENT_RECORDS
FROM ACCIDENTINFO A, ERROR E
WHERE A.ERRORCODE = E.ERRORCODE
GROUP BY A.ACCIDENTID, A.ACCIDENTZONE, A.ERRORCODE, A.CAR_DAMAGE_SEVERITY
ORDER BY A.ACCIDENTID;

SELECT * FROM ACCIDENT_FACT_V2;